from django.conf import settings

class ServerEnum:

    #Response CONSTANTS
    RESPONSE_CONNECTION_ERROR = "CONNECTION_ERROR"
    RESPONSE_SUCCESS = "SUCCESS"
    RESPONSE_DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
    RESPONSE_PASSWORD_MISMATCH = "PASSWORD_MISMATCH"
    RESPONSE_EMAIL_MISMATCH = "EMAIL_MISMATCH"
    RESPONSE_EMAIL_TAKEN = "EMAIL_TAKEN"
    RESPONSE_PHONE_TAKEN = "PHONE_TAKEN"
    RESPONSE_INVALID_JWT_TOKEN = "INVALID_JWT_TOKEN"
    RESPONSE_INVALID_GOOGLE_TOKEN = "INVALID_GOOGLE_TOKEN"
    RESPONSE_INVALID_PHONE_TOKEN = "INVALID_PHONE_TOKEN"


    DATABASE_INSERT = 'INSERT'
    DATABASE_UPDATE = 'UPDATE'

    #User Type
    USER_PARENT = "PARENT"
    USER_CHILD = "CHILD"





